### ISSUE TITLE
Links Getting Cached and Triggering Error

### ISSUE THREAD

**Issue by jakebrenner** [NiteshOswal/ezrtv3#1]
When creating a pro link I got an error. I then tried to submit another link (different URL) and received the same error but it showed the first URL so it appears to not be reseting even after a browser refresh. 
![screen shot 2017-04-27 at 10 32 57 pm](https://cloud.githubusercontent.com/assets/23482342/25515865/0976168c-2b9c-11e7-8a1d-1491320dcc0d.png)

**Comment by jakebrenner** [comment]
Also, we need to make sure that someone can just enter www.example.com and not have to add the http or https each time.

**Comment by NiteshOswal** [comment]
It'll default to using `http://` if nothing's present in terms of url scheme
