### ISSUE TITLE
My Links - Pro Users Allow Folders/Groups

### ISSUE THREAD

**Issue by jakebrenner** [NiteshOswal/ezrtv3#11]
I think that we talked about this a while back, but Pro Users should have the ability to create Groups of links or Folders so that they can organize their links rather than have them all together. The other option would be to allow for them to "Tag" a link (i.e. #KickstarterProject2) and then search/filter by those tags. Obviously if we go the Tag route then they would have to be able to add/edit/remove tags for each link.

**Comment by NiteshOswal** [comment]
Hmm, didn't talk about it, but I think it's possible, do you want this to
be a separate menu item? Or just as a tag in links?

**Comment by jakebrenner** [comment]
This should just be a grouping within the My Links area. I don't think it needs to be a new section. I'm thinking that there would be a column in the my links table that says "Tags" and in there it will show all the associated tags for that link. There will be a little edit icon in that area so if the user clicks that then a modal will open and they can easily add/edit/remove tags for that link. 

Additionally, if they click on one of the tags then it will filter to ONLY SHOW links that that tag. Above the table it should just say "Tags: #KickstaterProject2 " if that's the tag that they are filtering by. In that box there should be an "X" so if they close that out then it will go back to normal and just show all of the links since there is no tag filter being applied.
