### ISSUE TITLE
Edit Pro Link - PHP Variables Appearing

### ISSUE THREAD

**Issue by jakebrenner** [NiteshOswal/ezrtv3#13]
When you go to edit a Pro link there is a PHP variable that appears in the top left (see attached screenshot). This should be hidden so we don't show the end user that information.
![screen shot 2017-04-27 at 11 17 25 pm](https://cloud.githubusercontent.com/assets/23482342/25516517/e0f50f16-2b9f-11e7-8cce-b60030b24e7c.png)

**Comment by NiteshOswal** [comment]
Yeah saw that, my bad, will fix
