### ISSUE TITLE
Ad Multiple Facebook Accounts Not Working

### ISSUE THREAD

**Issue by jakebrenner** [NiteshOswal/ezrtv3#33]
Adding the first Facebook account was really easy, but then when I went to add another one it just keeps adding my same account over and over again. After the first account is added it should open the Facebook login window so the user can login to a new account.

Also, it should not let you add the same account multiple times. A notification should appear that says "You've already added this Facebook account to your Easy Retarget account"
![screen shot 2017-05-10 at 12 06 28 am](https://cloud.githubusercontent.com/assets/23482342/25886894/9b85b010-3514-11e7-9256-ece45e91d47b.png)

**Comment by NiteshOswal** [comment]
Well it does requires you to logout and login to a new account, if you're logged in, it'd go ahead and create the new account.

I can do something about duplicates tho.
