### ISSUE TITLE
JWT Not Configured Properly

### ISSUE THREAD

**Issue by jakebrenner** [NiteshOswal/ezrtv3#35]
I get the following error when I try to login. I've tried your email account as well as mine.

JWT is not configurated properly, please contact the admin

<img width="1494" alt="screen shot 2017-05-29 at 12 37 07 pm" src="https://cloud.githubusercontent.com/assets/23482342/26560450/8f24746c-446b-11e7-89d3-66092d3ac212.png">

**Comment by NiteshOswal** [comment]
So configured that properly, checking the rest of the things, and closing things

**Comment by NiteshOswal** [comment]
Something's still fishy with respect to data stored, investigating

**Comment by NiteshOswal** [comment]
ok fun alert, woocommerce uses a different endpoint for subscriptions! Good to know!

**Comment by NiteshOswal** [comment]
Just figured subscriptions, may have a different user and a different billing line! The more I know! 
*sorry for spamming*

**Comment by NiteshOswal** [comment]
And since you've already disabled anonymous orders, I'm switching to customers rather than billing line (because ofcourse it makes more sense, and I want to do that before I face your wrath)

**Comment by jakebrenner** [comment]
I'm not sure if you finished this on your end, but now I'm getting a login loop (if you're still working on this then disregard). See the attached message that pops up and then 
![screen shot 2017-05-30 at 10 13 42 am 2](https://cloud.githubusercontent.com/assets/23482342/26595590/cb9fdf20-4520-11e7-8688-a2807fbde4d0.png)
reidrects me back to the login page.

**Comment by NiteshOswal** [comment]
Imma working on it, needed to properly setup WordPress for jwt to work,
Forgot to replicate local settings :|

**Comment by jakebrenner** [comment]
ok, all good! I just wanted to pass that over. Thanks
